### ISSUE TITLE
 set up development environment correctly

### ISSUE THREAD

**Issue by SZhongheng** [nyu-software-engineering/fall-2019-spotterfly#8]
- [x] Download and install Visual Studio

- [x] Install npm, webpack, babel

This task is a part of #9

**Comment by SZhongheng** [comment]
This task is a part of #9

**Comment by bloombar** [comment]
@nyu-software-engineering/fall-2019-spotterfly - this is a Spike, not a Task, since there is no user story associated with it.  please update.
